#215 - underline states on row hover, navigate on click
Hyperobjekt/covid-19-behind-bars pull request #243
Opened 2021-03-18 16:52 UTC by hoshmn

2021-03-18 16:54 UTC, hoshmn commented on packages/gatsby-ucla-site/src/components/home/VaccineTable.js
> +      } else if (jurisdiction && isIce) {
don't technically need the `jurisdiction &&`

2021-03-18 16:55 UTC, hoshmn commented on packages/gatsby-ucla-site/src/components/home/VaccineTable.js
> +    "& tr:hover $clickable": {
or... `linked`? `linked-name`?

2021-03-18 18:41 UTC, Lane requested changes
looks good, a couple small fixes and then it's good to merge

2021-03-18 18:41 UTC, Lane commented on packages/gatsby-ucla-site/src/components/home/HomeTable.js
> +              <span
instead of a `<span>` with a click handler, this should be an `<a>` tag with an `href` attribute that links to the page for accessibility purposes.

also might as well move the inline style into the `classes.state` definition, we should work to remove inline styles where possible.

2021-03-18 18:41 UTC, Lane commented on packages/gatsby-ucla-site/src/components/home/VaccineTable.js
> +              <span
same as the other table, use an `<a>` tag for links and use a class for styling instead of inline style

2021-03-19 16:56 UTC, hoshmn commented on packages/gatsby-ucla-site/src/components/home/HomeTable.js
> +              <span
heh yeah, not really sure what I was thinking here...

2021-03-19 17:04 UTC, merged