Feature/time series v2 rebased
Hyperobjekt/covid-19-behind-bars pull request #378
Opened 2021-06-15 20:00 UTC by hoshmn

Initialize the FacilitiesTimeSeries app, following [this blueprint](https://github.com/Hyperobjekt/covid-19-behind-bars/blob/release/v2.0.0/notes/time-series-planning.md).

Adds logic to gatsby-node to grab the UCLA data, parse it, and write it to csvs (one for each state). Also writes a csv listing all facilities. On the FE, adds visx to visualize the data.

Are we thinking this would be extracted as a reusable component? If so let me know your thoughts and I can extract a generic component (/set of components).

2021-06-15 20:03 UTC, hoshmn commented on src/common/hooks/use-time-series-data.js
> +import { csv } from "d3-fetch";
Probably easiest to understand this file by starting at 75 `return useMemo` and referencing helper fns as they're called. Storing the parsedFacilityMap on state as well as loadedStateDatamap isn't strictly necessary and adds a little more complexity, but seems worth it since otherwise for every change in facility selection all facility data will need to be extracted and parsed again from the state data.

2021-06-15 20:04 UTC, hoshmn commented on scripts/parseData.js
> -/**
moved to `/utils.js`

2021-06-15 20:04 UTC, hoshmn commented on scripts/utils.js
> +  "bop",
alphabetized and added BOP

2021-06-15 20:05 UTC, hoshmn commented on gatsby-node.js
> +  loadTimeSeries();
I went with async since nothing downstream in the build should depend on it. If that could cause issues, I can change to sync.

2021-06-15 20:12 UTC, hoshmn commented on src/common/utils/formatters.js
> +};
For labeling the selected options and plot lines.

2021-06-16 17:18 UTC, Lane requested changes
@hoshmn nice work, this looks great so far! a few requests for minor changes:

- [ ] slugify output file names and add CSV file extension (e.g. `North Carolina` -> `north-carolina.csv`)
- [ ] move `loadTimeSeries()` to a more appropriate place, wait for the promise to resolve (just in case)
- [ ] parse data state by state as data is loaded instead of facility by facility to reduce complexity and state items
- [ ] drop `useCallback` in `useTimeSeriesData` hook, as it doesn't result in performance gains and could cause bugs due to missing dependencies.

2021-06-16 17:18 UTC, Lane commented on src/common/hooks/use-time-series-data.js
> +    csv("./data/" + state)
parsing data is very fast, so i think it'd be easier to parse the data set as it comes in and store the parsed data in the store instead of storing the data as is and parsing individual facilities.



e.g. the entire contents of this hook would be something like:

```js

  /** Returns data for selectedFacilities, and loads the data if unavailable */
  return useMemo(() => {
    // bring loadStateData into the useMemo hook,
    // so it is not needed as a dependency
    const loadStateData = (state) => {
      if (loadedStateDataMap[state]) return;
      csv("./data/" + state, parseTimeSeries)
        .then((d) => {
          loadedStateDataMap[state] = d;
          console.log(`DATA LOADED FOR ${state}`);
          setLoaded(state, loadedStateDataMap);
        })
        .catch((err) => {
          console.error(
            `Failed to load ${state} time series data due to: ${err}`
          );
        });
    };

    // map selected facilities to the parsed data in `loadedStateMap`
    return selectedFacilities
      .map(({ state, name, id }) => {
        // check for loaded data
        if (!loadedStateDataMap[state]) {
          loadStateData(state);
          return null; // null value while data is loading
        }
        return loadedStateDataMap[state].find((fac) => fac.id === id);
      })
      .filter(Boolean); // remove null values that are loading
  // ensure all state dependencies are included in dependency array
  }, [selectedFacilities, loadedStateDataMap, setLoaded]);
```

this way, you elimated the need for `getParsedFacilityData` and tracking which facilities have been parsed.

2021-06-16 17:18 UTC, Lane commented on src/components/FacilitiesTimeSeries/useTimeSeriesStore.js
> +const useTimeSeriesStore = create((set, get) => ({
with some refactoring of the `useTimeSeriesData` hook above, the following state should no longer be needed:

- parsedFacilityMap
- setParsedFacilityMap
- loadedStates (could replace this with an isStateLoaded function that checks if `loadedStateDataMap` has a corresponding key, if needed)

2021-06-16 19:29 UTC, Lane commented
just noticed one more thing.  when using a zustand store, you want to make sure you are only pulling the required items out of the store.

e.g. right now there is this:

```js
const {
  selectedFacilities,
  loadedStates,
  loadedStateDataMap,
  setLoaded,
  parsedFacilityMap,
  setParsedFacilityMap,
} = useTimeSeriesStore((state) => state, shallow);
```

the selector (`(state) => state`) returns the entire store state, and uses a shallow comparison to check for changes.  due to the selector returning the entire state, this will trigger the hook to run whenever _any_ value in the store changes, even values you aren't using (e.g. `selectedMetric`)

ideally, we only want this hook to run when the values we are using change.  so, the selector should be updates so it looks something like this:

```js
const {
  selectedFacilities,
  loadedStates,
  loadedStateDataMap,
  setLoaded,
  parsedFacilityMap,
  setParsedFacilityMap,
} = useTimeSeriesStore(
  (state) => ({
    selectedFacilities: state.selectedFacilities,
    loadedStates: state.loadedStates,
    loadedStateDataMap: state.loadedStateDataMap,
    setLoaded: state.setLoaded,
    parsedFacilityMap: state.parsedFacilityMap,
    setParsedFacilityMap: state.setParsedFacilityMap,
  }),
  shallow
);
```

with this, the hook will only run when the values we are using in the store change (instead of when any value changes).

lastly, it's up to personal preference but i find that array destructuring is a little less typing than the object destructuring:

```js
const [
  selectedFacilities,
  loadedStates,
  loadedStateDataMap,
  setLoaded,
  parsedFacilityMap,
  setParsedFacilityMap,
 ] = useTimeSeriesStore(
  (state) => [
    state.selectedFacilities,
    state.loadedStates,
    state.loadedStateDataMap,
    state.setLoaded,
    state.parsedFacilityMap,
    state.setParsedFacilityMap,
  ],
  shallow
);
```

2021-06-21 21:54 UTC, hoshmn commented
> just noticed one more thing. when using a zustand store, you want to make sure you are only pulling the required items out of the store.

_d'oh!_ makes sense, thanks for the explanation

2021-06-21 22:02 UTC, hoshmn commented on src/common/hooks/use-time-series-data.js
> +          // loadedStateDataMap[state] = d;
clone state rather than mutating

2021-06-21 22:15 UTC, hoshmn commented on src/common/hooks/use-time-series-data.js
> +    csv("./data/" + state)
makes sense, sounds like a cleaner way to go about it. i made essentially these changes, just one last question: my first implementation used `loadedStates` as a (admittedly non-idiomatic) way to avoid recreating the `loadedStateDataMap` every time a new state is loaded (since, containing all the loaded states' parsed facilities, it could grow quite large as more states are loaded) by instead just mutating that piece of state (I know I know, not the best practice :)). I've now [changed](https://github.com/Hyperobjekt/covid-19-behind-bars/pull/378/files#r655733223) the logic to clone rather than mutate, so having `loadedStateDataMap` in the above dependency array does properly trigger a recalculation and `loadedStates` isn't needed. I assume this is the better approach, and we can trust garbage collection to get rid of the out-of-date `loadedStateDataMaps` (/maybe they're size is pretty trivial in the scheme of things anyways?)?

2021-06-23 00:13 UTC, Lane commented
@hoshmn this is looking good, thanks for the updates!  do you want me to merge this branch into the `release/v2.0.0` or do you want to continue developing the time series in this branch?

2021-07-02 15:28 UTC, Lane commented
closing this PR, replaced by #399

2021-07-02 15:28 UTC, closed without merging