Feature/time series v2 round2
Hyperobjekt/covid-19-behind-bars pull request #399
Opened 2021-06-26 19:10 UTC by hoshmn

Follow up to #378 with implementation of a handful of UI/UX items, to conform to [designs](https://www.figma.com/file/TKdSksUXJjYDl9FePrEiZz/UCLA---CBB---Style-guide%2C-Site-map?node-id=1611%3A0), including:
- Facility Select
  - convert to modal interface
  - style the "chips" with a color tag
- sample axis tick date formatting

2021-06-26 19:11 UTC, hoshmn commented on src/components/FacilitiesTimeSeries/components/TimeSeriesChart.js
> +};;;;
sometimes prettier does this to me 😭

2021-06-26 19:15 UTC, hoshmn commented on src/components/FacilitiesTimeSeries/components/FacilitySelect.js
> +          value={selectedFacilities}
didn't seem to be an out-of-the-box solution to make this a modal, so I use one non-interactive Autocomplete to display the selected facilities, and when you click it it opens a modal with the "real" one. this could be DRYed up a bit by extracting a `getAutocomplete` function

2021-06-26 19:16 UTC, hoshmn commented on src/components/FacilitiesTimeSeries/components/TimeSeriesChart.js
> +  const formatDate = (date, i, allTicks) => {
not sure this is the exact date formatting we want, but it's a start

2021-06-28 22:49 UTC, Lane commented on src/components/FacilitiesTimeSeries/components/TimeSeriesChart.js
> +};;;;
super weird, prettier cleans it up when i open the file and save.  wonder if there is a bug in the version you have?  no big deal if it's not a quick fix.

2021-06-28 23:33 UTC, Lane commented on src/components/FacilitiesTimeSeries/components/FacilitySelect.js
> +          value={selectedFacilities}
gotcha, we should avoid using the autocomplete here if it's not the intended control.  for proper semantics, this should be a list of location chips, with a button element that triggers the dialog.

e.g. something like: 

```
<Box className="facilities" position="relative" display="flex" pr={5}>
  <Box className="facilities__list" component="ul" display="flex">
    {selectedFacilities.map((facility, i) => (
      <Chip
        classes={{ root: classes.chip }}
        component="li"
        icon={
          <FiberManualRecord style={{ fill: getFacilityColor(i) }} />
        }
        label={facility.name}
        onDelete={null}
      />
    ))}
  </Box>
  <Box
    clone
    position="absolute"
    width="100%"
    height="100%"
    justifyContent="flex-end"
  >
    <Button className="facilities__action" onClick={openHandler}>
      <ArrowDownward aria-label="edit facilities" />
    </Button>
  </Box>
</Box>
```

using the box inline properties for styling.  the main takeaways here are:

- uses `<ul>` tag for list of facilities
- uses `<li>` tag for each facility
- uses `<button>` tag for dialog trigger

this will ensure assistive technologies are able to read the content, dictate the controls, and set focus to the proper elements.

we should also be sure to add [appropriate `aria-labelledby` attributes](https://material-ui.com/components/modal/#accessibility) on the dialog + title.

2021-06-28 23:35 UTC, Lane commented on src/components/FacilitiesTimeSeries/components/TimeSeriesChart.js
> +  const formatDate = (date, i, allTicks) => {
this is great!

2021-06-28 23:48 UTC, Lane requested changes
@hoshmn this is looking good so far! only a couple touchups as indicated in the comment:

- switch out autocomplete on page with list of chips + button
- add `aria-labelledby` to the dialog tag, referencing the title

>chart legend. I'm not sure there will be a straightforward way of implementing this as designed based on this - if the legend is a separate HTML element than the SVG chart, lining up the facility names with the corresponding line seems tricky. 

agreed, could we use an annotation for the last point on the line to achieve this?  i modified their [codesandbox with an annotation example](https://codesandbox.io/s/xychart-legend-demo-forked-08ef0).

2021-06-28 23:49 UTC, Lane commented
whoops, i linked the original codesandbox instead of my fork.  here's the proper link: https://codesandbox.io/s/xychart-legend-demo-forked-08ef0

2021-06-30 19:11 UTC, hoshmn commented on src/components/FacilitiesTimeSeries/components/FacilitySelect.js
> +          )}
show max 4 and then "+n"

2021-06-30 19:12 UTC, hoshmn commented on src/components/FacilitiesTimeSeries/components/TimeSeriesChart.js
> +              /> */}
Experimenting with putting a marker in front of the label

<img width="1280" alt="Screen Shot 2021-06-30 at 1 44 52 PM" src="https://user-images.githubusercontent.com/18331999/124018165-8d6d7180-d9b5-11eb-9ee7-2f43f6696828.png">

2021-06-30 19:13 UTC, hoshmn commented on src/components/FacilitiesTimeSeries/components/TimeSeriesChart.js
> +      margin={{ top: 55, right: 150, bottom: 55, left: 55 }}
maybe the 150 should be stored as a variable to keep in sync with the AnnotationLabel width

2021-06-30 19:15 UTC, hoshmn commented on scripts/loadTimeSeriesData.js
> +
made these changes to prevent situations like the one below (but keep null values that form gaps in the lines, as that seems valuable to preserve)
<img width="719" alt="Screen Shot 2021-06-30 at 2 17 35 PM" src="https://user-images.githubusercontent.com/18331999/124018426-d6bdc100-d9b5-11eb-9fe8-a9b99f2167e5.png">

2021-06-30 19:22 UTC, hoshmn commented
> agreed, could we use an annotation for the last point on the line to achieve this? i modified their [codesandbox with an annotation example](https://codesandbox.io/s/xychart-legend-demo-forked-08ef0).

This could work, but labels will often overlap (see below). We could add logic to offset them vertically, but if a user adds enough lines they'll eventually overlap (and the fact that the long facility names quickly span multiple lines makes it even trickier). Also our control is constrained by the fact that AnnotationLabel just takes a string (as "title") to set as its content, rendered as an SVG).

<img width="675" alt="Screen Shot 2021-06-30 at 3 07 50 PM" src="https://user-images.githubusercontent.com/18331999/124018839-4af86480-d9b6-11eb-98ac-39f6ad06c5f6.png">

2021-07-02 19:32 UTC, Lane commented
superseded by #407

2021-07-02 19:32 UTC, closed without merging