Feat/525 states notes
Hyperobjekt/covid-19-behind-bars pull request #607
Opened 2021-10-28 18:23 UTC by hoshmn

@Lane I pulled out all the Scrollama stuff to simplify/standardize the states page with the others. Should we also remove the white background "cards" that sections get on the states page for mobile? Those styles are applied to StepWrapper, so no other pages used them and after my conversion they're currently just left on the Aggregates and Grassroots tables (those components are implemented using StepWrapper). Let me know and I can clean up/tear out those last usages. 

closes #525

2021-11-01 23:45 UTC, Lane requested changes
@hoshmn thanks for this and taking a pass at the state page cleanup!  there are a few minor style things i wanted to touch up, and also dropped some of the components we are no longer using in #614.  can you take a look and merge that into this branch if it is all good with you?

after that, i think we should adjust the "notes" cms widget to use a select for the all / state name options, just to cut down on the chance of user error.  i added some notes in a commend for that.

after that, this is good with me!

2021-11-01 23:45 UTC, Lane commented on src/cms/lang/sections/notes.js
> +    makeStringField("key", {
can we switch to a select widget here so they can select from state names + all options instead of having to manually type the state in lower case?  could see it being too easy for them to accidentally make a typo here and have it not work as expected.

you should be able to import the [us_states.json](https://github.com/Hyperobjekt/covid-19-behind-bars/blob/development/data/us_states.json) in this repo (or pull in from another source if there's one you prefer) and generate select options from that.

2021-11-03 02:40 UTC, hoshmn commented on src/cms/lang/sections/scorecard.js
> +export const getScorecard = (noteOptions) => {
not sure if this is the cleanest approach, but it's what seemed the best balance to me. 

basically i didn't want to add "federal" and "immigration" to the dropdown selection in notes because then it might feel like you can set the ICE scorecard notes from the States CMS page and vice versa. also didn't want to define multiple duplicate `scorecard` CMS configs for States/ICE/BOP with just differing `notes` sections. if it's a preferable pattern i could instead 1) avoid using updateField at all and give `notes` a `getNotes(options)` method, or 2) use updateField to update the notes options in `scorecard` directly in federal.js/immigration.js -- but would need to copy many levels deep because of the mutation (maybe worth pulling in a deepClone method in that case...)

2021-11-03 02:44 UTC, hoshmn commented on src/cms/lang/sections/notes.js
> +    makeStringField("key", {
good call. just had to finagle `scorecard` a bit so that the ICE/BOP versions don't have all the states as options, see [comment](https://github.com/Hyperobjekt/covid-19-behind-bars/pull/607/files#r741582990)

2021-11-04 16:25 UTC, ekmason commented
@hoshmn I'm noticing that if I execute a search, navigate to one of the search result pages, then click into the search component again, I see this view and am unable to enter a query into the search box. Any thoughts on what might be happening? (screenshot attached) 

![image](https://user-images.githubusercontent.com/80919000/140378922-cb7c018e-8ae0-41de-90b1-483e39a6d5e1.png)

2021-11-17 19:27 UTC, hoshmn commented
merged

2021-11-17 19:27 UTC, closed without merging