Feature/time series update
Hyperobjekt/covid-19-behind-bars pull request #642
Opened 2021-11-30 20:50 UTC by hoshmn

@Lane @ekmason 

fixes #20 

**Notes**:
1) I am using Web.Group value directly in the tooltip. These are all the Web.Group/Jurisdiction designations currently applied to the data:

| Web.Group | Jurisdiction |
| --- | --- |
| Prison | State |
| County | County |
| Juvenile | State |
| Juvenile | County |
| ICE | Immigration |
| Federal | Federal |

2) I added a sample data note which UCLA may wish to update in the CMS.

3) One of their default facilities ("East Texas Unit") is on their exclusion list, so will no longer appear. I replaced it with Tennessee's "Bledsoe County Correctional Complex" (somewhat random choice, just saw that it had more data than most). These can be configured in the CMS

4) I'm naming the "Federal" rows in the statewide csv they added (historical_state_counts.csv) "All BOP Facilities". I mention this because in the previous data set they had "All BOP Residential Reentry Centers", but I take it that that was different data. I'm naming the "ICE" rows "All ICE Facilities", which was the name used in the old data set.

2021-11-30 23:49 UTC, Lane commented
thanks @hoshmn! a few requests:

1.  can you set the jurisdiction label based on a combination of the `web.group` and `jurisdiction` columns?  they should match up with language we are using in the spike legend / tables.

| Web.Group | Jurisdiction | Jurisdiction Label |
| --- | --- | :--- |
| Prison | State | State Prison |
| County | County | County Jail |
| Juvenile | State | State Youth Facility |
| Juvenile | County | Local Youth Facility |
| ICE | Immigration | ICE Detention Center |
| Federal | Federal | Federal Prison |

implementation-wise, maybe add some entries to the language object based on the `Web.Group` and `Jurisdiction` combination:  `LABEL_{Web.Group}_{Jurisdiction}` (e.g. "LABEL_FEDERAL_FEDERAL": "Federal Prison").  or, if you have better ideas feel free.

2. style to match other tooltips on the site.  tooltips throughout the size used a fixed size (14px i think) and remain consistently sized across viewports.  the time series tooltip is larger on larger viewports.  also the tooltip background seems to be a different color in the time series.

**time series**:
![image](https://user-images.githubusercontent.com/21034/144144900-5c92a07d-07db-44e1-b19d-19ce46f4e090.png)

**facilities map (state page)**:
![image](https://user-images.githubusercontent.com/21034/144144938-1c53c253-fa82-426e-b311-b4ea917e17be.png)

3. move date on tooltip to the body.  let's keep the header of the tooltip for facility identification (name, state, jurisdiction) and the body for displaying the data for the given point (date, corresponding data value).  should look something like this:

![image](https://user-images.githubusercontent.com/21034/144146208-1dc82b13-f7ad-438c-bf91-be2ca08eab0f.png)

2021-11-30 23:57 UTC, Lane requested changes
in addition to the changes above, need to also update the CMS config so optional fields are not required.

2021-11-30 23:57 UTC, Lane commented on src/cms/lang/home.js
> +        makeStringField("Data Link Text"),
need to add `{required: false}` as a second param to `makeStringField` for optional fields or else it will not allow submission with an empty value:

![image](https://user-images.githubusercontent.com/21034/144146747-3f51a2fc-0aff-42fc-8263-2f27354d0dbc.png)

2021-12-03 00:47 UTC, hoshmn commented on src/components/FacilitiesTimeSeries/components/TimeSeriesTooltip.js
> +                  "MMMM D, YYYY"
I changed this from MMM so it now shows the whole month. (Guessing it was just copied over from the axis ticks, which need to be abbreviated for space.) Feel free to revert if you prefer the abbreviation.

2021-12-03 00:51 UTC, hoshmn commented on src/components/FacilitiesTimeSeries/components/TimeSeriesTooltip.js
> +    backgroundColor: "rgba(32, 32, 32, 0.9) !important",
I extracted this tooltip as its own file since TimeSeriesChart is getting bloated. Replaced spans & divs with mui components and replaced inline styles with these. Needed just this one "important" to override an inline style applied to the visx Tooltip component.

2021-12-06 20:04 UTC, Lane commented
thanks for the updates @hoshmn!  i was still seeing a few style inconsistencies between the time series tooltip and facilities tooltips.

i did some additional refactoring in #643, can you review and merge in if it looks good to you?

lastly, noticing we still get some tooltips when data is unavailable for all locations:

![image](https://user-images.githubusercontent.com/21034/144914305-428ffa0f-6279-4485-8ddd-a9d40f15162c.png)

can we adjust to either show no tooltip in this case, or have it say something like "no data available for {metric} among {group}"?

2021-12-07 02:56 UTC, hoshmn commented
@Lane thanks for extracting those generic components! And good catch -- if there's no data plotted I feel like no tooltip should appear. If there's no data plotted, the `nearestDatum` found has a distance of `Infinity`, so I added an early return for that case.

2021-12-08 17:46 UTC, ekmason commented
Issue Tracker is [here](https://docs.google.com/spreadsheets/d/1bVlLIeewGnD6B_WvdFa8vqXI-lv6GM-ySs5J8jmKmc8/edit#gid=0), but I'll add change requests as comments here once triaged.

2021-12-09 23:27 UTC, hoshmn commented
![Screen Shot 2021-12-09 at 3 18 05 PM](https://user-images.githubusercontent.com/18331999/145491488-75ea2a67-db8f-4126-b02b-0c4811562d6d.png)
@Lane is the note below the chart meant to be centered on lg when it gets a max-width?

![Screen Shot 2021-12-09 at 3 18 19 PM](https://user-images.githubusercontent.com/18331999/145491496-926fb5b5-282b-464a-81ef-a08a42d601f8.png)

2021-12-09 23:28 UTC, hoshmn commented on src/components/FacilitiesTimeSeries/components/TimeSeriesChart.js
> +    background: "#fbeeee",
notification colors could be added to theme

2021-12-09 23:30 UTC, hoshmn commented on src/components/FacilitiesTimeSeries/components/TimeSeriesChart.js
> +      maxWidth: "28em",
bumped this slightly to match the width of the button group below it (but also not sure if this is meant to be centered)

2021-12-14 20:30 UTC, ekmason commented
@hoshmn Liz has approved this for release with the following changes: 

Add the following data note to the Time Series data notes
> All data reflect information reported by carceral agencies. Testing and reporting practices vary widely by agency. True counts are likely higher and may be significantly higher than reported

Set the following defaults for the chart: 
- metric: "Active cases" among "Incarcerated people"
- facilities: Los Angeles County Jails; All State Prisons, Arkansas; Bellamy Creek Correctional Facility, Michigan

Add a direct url (https://uclacovidbehindbars.org/timeseries)

2021-12-15 19:51 UTC, Lane approved these changes

2021-12-15 19:52 UTC, merged